#version: '3.8'
services:
  postgis-local:
    privileged: true
    image: postgis-local:14-3.4
    build:
      context: ./
      dockerfile: Dockerfile.txt
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: IJX8LRlUIY4TB7Vw7EDZ
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ~/docker-data/pg14/data:/var/lib/postgresql/data
